name = "blog-nextjs-image"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "npm ci --silent && npm run build"
[build.upload]
format = "service-worker"
